name: ${{ parameters.major }}.${{ parameters.minor }}.${{ parameters.patch }}$(rev:.r)

pr: none
trigger:
  branches:
    include:
    - main
    - feature/*
  paths:
    include:
    - /src/customer.azure.invictus

parameters:
- name: major
  displayName: Major Version
  type: string
  default: 4
- name: minor
  displayName: Minor Version
  type: string
  default: 15
- name: patch
  displayName: Patch Version
  type: string
  default: 10
- name: useBeta
  displayName: Use Beta
  type: string
  default: $False

pool:
  vmImage: 'windows-latest'

stages:
- stage: Package
  displayName: Package
  dependsOn: []
  variables:
  - group: invictus.installation
  jobs:
  - job: publish
    displayName: Build and Publish Framework
    steps:
    - checkout: self
      clean: true
      persistCredentials: true

    - template: ./Templates/build-steps.yaml
      parameters:
        type: 'framework'
        useBeta: '${{ parameters.useBeta }}'
        storageAccountName: '$(Invictus.Installation.StorageAccount.Name)'
        storageSasToken: '$(Invictus.Installation.StorageAccount.Framework.SasToken)'