blank_issues_enabled: false
contact_links:
  - name: 💬 Discuss something Invictus
    url: https://github.com/invictus-integration/docs-ifa/discussions/new
    about: Ask a question, praise, speculate ideas or request support for using Invictus.