name: 💪 Enhance request
description: Suggest an improvement to the Invictus product.
title: '💪 [Enhance]: '
labels:
  - enhancement
  - triage
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your contribution to the Invictus product!
  - type: input
    id: invictus-version
    attributes:
      label: Version
      description: What version of the product are you running?
      placeholder: Ex. 6.0.0
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Is your enhancement request related to a problem? Please describe.
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when...
  - type: textarea
    id: context
    attributes:
      label: Additional context
      placeholder: Add the link to the page(s) or any other context/screenshots related to the enhancement request here.
