name: 💪 Enhancement request
description: Suggest an improvement to the Invictus project.
title: "💪 [Enhancement]: "
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thanks for you contribution to the Invictus project!
  - type: dropdown
    id: invictus-category
    attributes:
      label: Category
      description: In what area of the project does this enhancement belong?
      multiple: true
      options:
        - Dashboard visualization
        - Framework components
        - Documentation
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Is your enhancement request related to a problem? Please describe.
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when...
  - type: textarea
    id: context
    attributes:
      label: Additional context
      placeholder: Add the link to the page(s) or any other context/screenshots related to the enhancement request here.
on:
  issues:
    types:
      - opened
jobs:
  move-issue-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Move issue to project column
        uses: actions/add-to-project@v1
        with:
          project-url: https://github.com/orgs/invictus-integration/projects/2
          column-name: 'To evaluate'
          github-token: ${{ secrets.GITHUB_TOKEN }}     