/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Invictus - Integration",
  "url": "https://invictus-integration.github.io",
  "baseUrl": "/",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "favicon": "img/favicon.ico",
  "organizationName": "invictus-integration",
  "projectName": "Invictus - Integration",
  "themeConfig": {
    "image": "images/v2_logo_horizontal.png",
    "navbar": {
      "title": "Integration",
      "logo": {
        "alt": "Invictus",
        "src": "images/v2_logo_horizontal.png",
        "srcDark": "images/v2_logo_horizontal.png"
      },
      "items": [
        {
          "type": "docsVersionDropdown",
          "position": "right",
          "dropdownItemsBefore": [],
          "dropdownActiveClassDisabled": true,
          "docsPluginId": "default",
          "dropdownItemsAfter": []
        },
        {
          "type": "search",
          "position": "right"
        },
        {
          "href": "https://github.com/invictus-integration/docs-ifa",
          "label": "GitHub",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Community",
          "items": [
            {
              "label": "Invictus Integration Github",
              "href": "https://github.com/invictus-integration/docs-ifa"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2025, Invictus - Integration maintained by Codit"
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#19203d",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(162, 191, 252)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "hsl(5, 74%, 59%)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "inserted",
              "attr-name"
            ],
            "style": {
              "color": "hsl(119, 34%, 47%)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "hsl(230, 4%, 64%)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "string",
              "url"
            ],
            "style": {
              "color": "hsl(119, 34%, 47%)"
            }
          },
          {
            "types": [
              "variable"
            ],
            "style": {
              "color": "#249cff"
            }
          },
          {
            "types": [
              "number"
            ],
            "style": {
              "color": "hsl(35, 99%, 36%)"
            }
          },
          {
            "types": [
              "builtin",
              "char",
              "constant",
              "function",
              "operator"
            ],
            "style": {
              "color": "#249cff"
            }
          },
          {
            "types": [
              "punctuation"
            ],
            "style": {
              "color": "#19203d"
            }
          },
          {
            "types": [
              "selector",
              "doctype"
            ],
            "style": {
              "color": "#19203d",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "class-name"
            ],
            "style": {
              "color": "hsl(35, 99%, 36%)"
            }
          },
          {
            "types": [
              "tag",
              "keyword"
            ],
            "style": {
              "color": "hsl(301, 63%, 40%)"
            }
          },
          {
            "types": [
              "boolean"
            ],
            "style": {
              "color": "hsl(35, 99%, 36%)"
            }
          },
          {
            "types": [
              "property"
            ],
            "style": {
              "color": "hsl(5, 74%, 59%)"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.8
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#e9edfa",
          "backgroundColor": "#19203d"
        },
        "styles": [
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(162, 191, 252)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "hsl(5, 74%, 69%)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "inserted",
              "attr-name"
            ],
            "style": {
              "color": "hsl(119, 34%, 67%)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "hsl(230, 4%, 74%)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "string",
              "url"
            ],
            "style": {
              "color": "hsl(119, 34%, 67%)"
            }
          },
          {
            "types": [
              "variable"
            ],
            "style": {
              "color": "#47acff"
            }
          },
          {
            "types": [
              "number"
            ],
            "style": {
              "color": "hsl(35, 99%, 66%)"
            }
          },
          {
            "types": [
              "builtin",
              "char",
              "constant",
              "function",
              "operator"
            ],
            "style": {
              "color": "#47acff"
            }
          },
          {
            "types": [
              "punctuation"
            ],
            "style": {
              "color": "#e9edfa"
            }
          },
          {
            "types": [
              "selector",
              "doctype"
            ],
            "style": {
              "color": "#e9edfa",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "class-name"
            ],
            "style": {
              "color": "hsl(35, 99%, 66%)"
            }
          },
          {
            "types": [
              "tag",
              "keyword"
            ],
            "style": {
              "color": "hsl(301, 63%, 80%)"
            }
          },
          {
            "types": [
              "boolean"
            ],
            "style": {
              "color": "hsl(35, 99%, 66%)"
            }
          },
          {
            "types": [
              "property"
            ],
            "style": {
              "color": "hsl(5, 74%, 69%)"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.8
            }
          }
        ]
      },
      "additionalLanguages": [
        "csharp",
        "fsharp",
        "diff",
        "json",
        "powershell"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "presets": [
    [
      "@docusaurus/preset-classic",
      {
        "docs": {
          "sidebarPath": "C:\\dev\\github.com\\invictus-docs\\sidebars.js",
          "routeBasePath": "/",
          "path": "preview",
          "sidebarCollapsible": false,
          "editUrl": "https://github.com/invictus-integration/docs-ifa/edit/master",
          "includeCurrentVersion": true
        },
        "theme": {
          "customCss": "C:\\dev\\github.com\\invictus-docs\\src\\css\\custom.css"
        }
      }
    ]
  ],
  "stylesheets": [
    "https://fonts.googleapis.com/css2?family=Bitter:wght@700&family=Inter:wght@400;500&display=swap"
  ],
  "baseUrlIssueBanner": true,
  "i18n": {
    "defaultLocale": "en",
    "path": "i18n",
    "locales": [
      "en"
    ],
    "localeConfigs": {}
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "scripts": [],
  "headTags": [],
  "clientModules": [],
  "tagline": "",
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  }
};
