name: Search broken links in PR
on:
  push:
    branches: [ master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]
jobs:
  check-links:
    name: runner / dead link check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run dead link check
        uses: AlexanderDokuchaev/md-dead-link-check@v0.9