on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest commit
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Install dependencies
        run: npm install
      - name: Run Cypress tests
        run: |
          npm run test
